### PR TITLE
Improve pitch diagram

### LINKED ISSUE #26: Improve pitch diagram
I understand if this isn't something you want to consider, but I find the pitch notation used in the dictionary unintuitive and think it can be improved.

For example:
image
image

I think the reason I find this difficult is because I'm used to seeing the lines on the top rather than the bottom, so what's shown in this dictionary is the opposite of my expectation. For example, here's what Yomichan does:
image
image

Is it possible to show the lines on top as Yomichan does, and if so would you consider changing to this? (I feel like this is the more standard way to show it when using lines, so I suspect it's simply not possible, but if it *is* possible that would be great.)

Regardless of the above, would you consider adding in the other fairly standard notation of `[X]` *in addition to* the line notation (as shown in the above screenshots)? For example, `[0]` represents heiban and in all other cases the number in the brackets represents the mora after which the pitch drops. For those of us familiar with pitch accent, this notation is succinct and can be understood intuitively.

### PR DESCRIPTION
**Pull request by mymro**
Fixes #26 by adding the index as requested. Overline unfortunately appears to be ignored by kindle when the book is a dictionary

### CODE REVIEW

**Comment by jrfonseca** [comment]
Thanks

**Comment by seanblue** [comment]
@mymro I'm trying to understand this change to make sure it's right (seemed like there might be some edge cases with one or two mora words), but it's hard to tell since I'm not familiar with the code. That said, isn't `used_accent` from earlier in the file the exact number that needs to be rendered in all cases? Would it make sense to pass that along in the dictionary similar to `ac` instead of trying to reverse engineer it later in `format_pronunciations`? Sorry if I'm missing something obvious.

**Comment by mymro** [comment]
@seanblue We use two files for the pronunciation and ACCDB_unicode.csv uses a weird format. This means while used_accent is what we need,  we only get them from accents.tsv. We prefer data from ACCDB_unicode.csv  because we get more information (norpon, nasal). That is why we turn the used_accent into this weird format and why we do not have the position directly as a number. But feel free to also add the position to the ACCDB_unicode.csv parser.

**Comment by seanblue** [comment]
@mymro Ah, that makes sense. I took a look, but I'm having so much trouble figuring out what the numbers in `ACCDB_unicode.csv` mean that I wouldn't even know where to start. So I think for now I'll just take your word that this works, and I'll keep an eye out for issues just in case.

Will there be an updated version added to the official releases, or do I have to build this on my own to get the new formatting?

**Comment by mymro** [comment]
@seanblue you can download the new build from the github [actions](https://github.com/jmdict-kindle/jmdict-kindle/actions/runs/3490851034) under artifacts, as soon as it is done. For the release, @jrfonseca has to prepare a new one.

You were right about the edge cases. in the  ACCDB_unicode.csv there are pronunciations for compound words --> multiple pitch drops. I have fixed this in pull #29

**Comment by mymro** [comment]
@seanblue here you go: [link](https://github.com/jmdict-kindle/jmdict-kindle/suites/9367399665/artifacts/441196105)

**Pull request merged**
